import type { ScoreMethod } from '../score-support/types';

export const METHODS: Array<{ value: ScoreMethod; label: string; shortLabel: string; description: string }> = [
  {
    value: 'thpt',
    label: 'THPT',
    shortLabel: 'THPT',
    description: 'Tổng điểm 3 môn theo từng tổ hợp xét tuyển.',
  },
  {
    value: 'hb',
    label: 'Học bạ',
    shortLabel: 'Học bạ',
    description: 'Tổng điểm 3 môn học bạ theo từng tổ hợp xét tuyển.',
  },
  {
    value: 'dgnl',
    label: 'ĐGNL',
    shortLabel: 'ĐGNL',
    description: 'Điểm đánh giá năng lực lấy theo đợt thi cao nhất.',
  },
  {
    value: 'kh',
    label: 'Kết hợp THPT và Học bạ',
    shortLabel: 'Kết hợp',
    description: '02 môn thi tốt nghiệp THPT năm 2026 và 01 môn thay thế bằng điểm học bạ.',
  },
];

export const SUBJECT_CATALOG: Record<string, string[]> = {
  A00: ['Toán', 'Vật lý', 'Hóa học'],
  A01: ['Toán', 'Vật lý', 'Tiếng Anh'],
  A02: ['Toán', 'Vật lý', 'Sinh học'],
  A04: ['Toán', 'Vật lý', 'Địa lý'],
  B00: ['Toán', 'Hóa học', 'Sinh học'],
  B02: ['Toán', 'Sinh học', 'Địa lý'],
  B03: ['Toán', 'Sinh học', 'Ngữ văn'],
  C01: ['Ngữ văn', 'Toán', 'Vật lý'],
  C02: ['Ngữ văn', 'Toán', 'Hóa học'],
  C04: ['Ngữ văn', 'Toán', 'Địa lý'],
  D00: ['Toán', 'Ngữ văn', 'Ngoại ngữ'],
  D01: ['Ngữ văn', 'Toán', 'Tiếng Anh'],
  D03: ['Ngữ văn', 'Toán', 'Tiếng Pháp'],
  D07: ['Toán', 'Hóa học', 'Tiếng Anh'],
  D08: ['Toán', 'Sinh học', 'Tiếng Anh'],
  D09: ['Toán', 'Lịch sử', 'Tiếng Anh'],
  D10: ['Toán', 'Địa lý', 'Tiếng Anh'],
  D14: ['Ngữ văn', 'Lịch sử', 'Tiếng Anh'],
  D15: ['Ngữ văn', 'Địa lý', 'Tiếng Anh'],
  M00: ['Toán', 'Ngữ văn', 'Năng khiếu'],
  X01: ['Toán', 'Ngữ văn', 'Giáo dục kinh tế và pháp luật'],
  X02: ['Toán', 'Ngữ văn', 'Tin học'],
  X04: ['Toán', 'Ngữ văn', 'Công nghệ nông nghiệp'],
  X06: ['Toán', 'Vật lý', 'Tin học'],
  X07: ['Toán', 'Vật lý', 'Công nghệ công nghiệp'],
  X08: ['Toán', 'Tiếng Anh', 'Công nghệ nông nghiệp'],
  X09: ['Toán', 'Hóa học', 'Giáo dục kinh tế và pháp luật'],
  X14: ['Toán', 'Sinh học', 'Tin học'],
  X16: ['Toán', 'Sinh học', 'Công nghệ nông nghiệp'],
  X25: ['Toán', 'Tiếng Anh', 'Giáo dục kinh tế và pháp luật'],
  X26: ['Toán', 'Tin học', 'Tiếng Anh'],
  X28: ['Toán', 'Công nghệ nông nghiệp', 'Tiếng Anh'],
};
