spring.application.name=be
#port
server.port=8081

#mongodb url
#spring.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/KLTN?maxPoolSize=100&minPoolSize=0}
spring.mongodb.uri=mongodb+srv://vadolaxt:abcd123456@cluster0.ykyc4zw.mongodb.net/KLTN?appName=Cluster0

#redis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=
spring.data.redis.database=0

#project
FE_BASE_URL=${FE_URL:http://localhost:3000}
FASTAPI_BASE_URL=${FASTAPI_URL:http://localhost:8000/api}

#jpa
spring.data.mongodb.auto-index-creation=true
logging.level.org.springframework.data.mongodb.core.MongoTemplate=INFO

# logging
logging.level.org.springframework.web=DEBUG

#jwt
jwt.base64-secret=${JWT_SECRET:tybBIQtqJWNdlTayWJmWt6v5xOoYq4W6g/iBY6XZp+aLRMNhwpXhvRth4nravWlrn5cVbWfwtUXshmnW7+ZjGg==}
jwt.access-token-expire=${ACCESS_TOKEN_EXPIRE:900}
jwt.refresh-token-expire=${REFRESH_TOKEN_EXPIRE:604800}

#mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=xuantrung19022004@gmail.com
spring.mail.password=djogrprygkyirpzl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
mail-sender=xuantrung19022004@gmail.com

RESEND_API_KEY=${RESEND_KEY:re_G226JzQq_9g92HxceS8Va5cFkxpGiVW3c}
SEND_GRID_API_KEY=${SEND_GRID_KEY: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}

#gg auth
spring.security.oauth2.client.registration.google.client-id=655464563429-c45i97cc5isk764dbvjn0pt9fij8m41a.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email, profile

#cloudinary
cloudinary.cloud-name=${CLOUDINARY_NAME:dgqu3s9o0}
cloudinary.api-key=${CLOUDINARY_API_KEY:217897316811579}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:wbwr5zgjZlQ4zCLbH85DAOM4FGo}