spring.application.name=be
spring.mongodb.uri=mongodb://localhost:27017/KLTN?maxPoolSize=100&minPoolSize=0

#jpa
spring.data.mongodb.auto-index-creation=true
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

# logging
logging.level.org.springframework.web=DEBUG
#spring.mvc.log-request-details=true
#logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG

#port
server.port=8081

#jwt
jwt.base64-secret=tybBIQtqJWNdlTayWJmWt6v5xOoYq4W6g/iBY6XZp+aLRMNhwpXhvRth4nravWlrn5cVbWfwtUXshmnW7+ZjGg==
jwt.access-token-expire=100000
jwt.refresh-token-expire=8640000

#project
FE_BASE_URL=http://localhost:3000