spring.application.name=be
spring.mongodb.uri=mongodb://localhost:27017/KLTN?maxPoolSize=100&minPoolSize=0

#jpa
spring.data.mongodb.auto-index-creation=true
logging.level.org.springframework.data.mongodb.core.MongoTemplate=INFO

# logging
logging.level.org.springframework.web=DEBUG

#port
server.port=8081

#jwt
jwt.base64-secret=tybBIQtqJWNdlTayWJmWt6v5xOoYq4W6g/iBY6XZp+aLRMNhwpXhvRth4nravWlrn5cVbWfwtUXshmnW7+ZjGg==
jwt.access-token-expire=900
jwt.refresh-token-expire=604800

#mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=xuantrung19022004@gmail.com
spring.mail.password=djogrprygkyirpzl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#gg auth
spring.security.oauth2.client.registration.google.client-id=655464563429-c45i97cc5isk764dbvjn0pt9fij8m41a.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email, profile

#redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=
spring.data.redis.database=0

#project
FE_BASE_URL=http://localhost:3000